[formatter."c++"]
command = "clang-format"
options = ["-i"]
includes = ["*.c", "*.cpp", "*.cc", "*.h", "*.hpp"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.toml]
command = "prettier"
options = ["--write"]
includes = ["*.toml"]

[formatter.python]
command = "black"
includes = ["*.py"]
